//This code was automatically generated by running scripts/generate-i18n-messages.ts
//PLEASE DO NOT EDIT MANUALLY

/* spell-checker: disable */
const messages = {
    "P": ""
};

export default messages;
/* spell-checker: enable */
