//This code was automatically generated by running dist/bin/generate-i18n-messages.js
//PLEASE DO NOT EDIT MANUALLY

/* spell-checker: disable */
const messages = {};

export default messages;
/* spell-checker: enable */
