import * as fs from "fs";
import { join as pathJoin, resolve as pathResolve } from "path";
import { getBuildContext } from "../bin/shared/buildContext";
import { generateResources as generateThemeResources } from "../bin/keycloakify/generateResources";
import { runPostBuildScript } from "../bin/keycloakify/runPostBuildScript";
import { isInside } from "../bin/tools/isInside";
import { VITE_PLUGIN_SUB_SCRIPTS_ENV_NAMES } from "../bin/shared/constants";

/** Marks a directory as one a subsequent call is allowed to delete. */
const GENERATED_DIR_MARKER_BASENAME = ".keycloakify-generated-resources";

export namespace generateResources {
    export type Params = {
        /**
         * ⚠️ Deleted and recreated on every call: must be non existent, empty, or
         * generated by a previous call. Relative to the project directory.
         */
        resourcesDirPath: string;
        /** Defaults to `process.cwd()`. */
        projectDirPath?: string;
    };

    export type Result = {
        /** Absolute path of the generated directory. */
        resourcesDirPath: string;
    };
}

/**
 * The resource generation half of `npx keycloakify build`: no Maven, no `.jar`.
 * The bundler build must have run first, this reads its output.
 *
 * ⚠️ A build intermediate, not a directory Keycloak can consume: the
 * `META-INF/keycloak-themes.json` descriptor and the page aliases are applied by
 * `keycloakify build` when it packages the `.jar`, not here.
 *
 * ⚠️ An invalid Keycloakify configuration terminates the process instead of
 * rejecting.
 *
 * Native ES modules must import `"keycloakify/api.js"`.
 */
export async function generateResources(
    params: generateResources.Params
): Promise<generateResources.Result> {
    const { resourcesDirPath: resourcesDirPath_params, projectDirPath } = params;

    if (
        process.env[VITE_PLUGIN_SUB_SCRIPTS_ENV_NAMES.RUN_POST_BUILD_SCRIPT] !== undefined
    ) {
        throw new Error(
            [
                "generateResources() can't be called from within the Keycloakify Vite",
                "plugin's `postBuild` hook: that hook is run by this function, so calling",
                "it back would loop indefinitely."
            ].join(" ")
        );
    }

    if (resourcesDirPath_params.trim() === "") {
        throw new Error("generateResources(): `resourcesDirPath` can't be empty.");
    }

    const buildContext = getBuildContext({ projectDirPath });

    const resourcesDirPath = pathResolve(
        buildContext.projectDirPath,
        resourcesDirPath_params
    );

    // True for equal paths too, so the project directory itself is rejected along
    // with its ancestors.
    if (
        isInside({
            dirPath: resourcesDirPath,
            filePath: buildContext.projectDirPath
        })
    ) {
        throw new Error(
            [
                `generateResources(): \`resourcesDirPath\` (${resourcesDirPath}) is the`,
                `project directory or one of its parents. It is deleted before`,
                `generating, point it at a directory dedicated to this output.`
            ].join(" ")
        );
    }

    if (fs.existsSync(resourcesDirPath)) {
        if (!fs.statSync(resourcesDirPath).isDirectory()) {
            throw new Error(
                `generateResources(): \`resourcesDirPath\` (${resourcesDirPath}) exists and isn't a directory.`
            );
        }

        const dirEntryBasenames = fs.readdirSync(resourcesDirPath);

        if (
            dirEntryBasenames.length !== 0 &&
            !dirEntryBasenames.includes(GENERATED_DIR_MARKER_BASENAME)
        ) {
            throw new Error(
                [
                    `generateResources(): \`resourcesDirPath\` (${resourcesDirPath}) isn't`,
                    `empty and wasn't generated by generateResources(), refusing to delete`,
                    `it. Point at another directory, or delete this one yourself first.`
                ].join(" ")
            );
        }
    }

    if (!fs.existsSync(buildContext.projectBuildDirPath)) {
        throw new Error(
            [
                `generateResources(): the project build directory`,
                `(${buildContext.projectBuildDirPath}) doesn't exist. Run your bundler`,
                `build first, this generates the theme from its output.`
            ].join(" ")
        );
    }

    fs.mkdirSync(resourcesDirPath, { recursive: true });

    await generateThemeResources({
        resourcesDirPath,
        buildContext
    });

    // `generateThemeResources()` only recreates the directory for the theme types
    // that are actually implemented.
    if (!fs.existsSync(resourcesDirPath)) {
        throw new Error(
            [
                `generateResources(): no resources were generated. Check that your theme`,
                `implements at least one theme type (login, account, admin or email).`
            ].join(" ")
        );
    }

    fs.writeFileSync(
        pathJoin(resourcesDirPath, GENERATED_DIR_MARKER_BASENAME),
        Buffer.from(
            "Generated by keycloakify's generateResources(). This directory is deleted and recreated on every call.\n",
            "utf8"
        )
    );

    runPostBuildScript({
        resourcesDirPath,
        buildContext
    });

    return { resourcesDirPath };
}
