import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import * as fs from "fs";
import * as os from "os";
import { join as pathJoin } from "path";
import { VITE_PLUGIN_SUB_SCRIPTS_ENV_NAMES } from "keycloakify/bin/shared/constants";

const getBuildContextMock = vi.hoisted(() => vi.fn());
const generateThemeResourcesMock = vi.hoisted(() => vi.fn());
const runPostBuildScriptMock = vi.hoisted(() => vi.fn());

vi.mock("keycloakify/bin/shared/buildContext", () => ({
    getBuildContext: getBuildContextMock
}));
vi.mock("keycloakify/bin/keycloakify/generateResources", () => ({
    generateResources: generateThemeResourcesMock
}));
vi.mock("keycloakify/bin/keycloakify/runPostBuildScript", () => ({
    runPostBuildScript: runPostBuildScriptMock
}));

import { generateResources } from "keycloakify/api";

const MARKER_BASENAME = ".keycloakify-generated-resources";

let projectDirPath: string;

/** Mirrors the real primitive: wipes the output directory, then writes into it. */
function setGeneratorBehavior(
    behavior: "generates resources" | "generates nothing"
): void {
    generateThemeResourcesMock.mockImplementation(
        async (params: { resourcesDirPath: string }) => {
            fs.rmSync(params.resourcesDirPath, { recursive: true, force: true });

            if (behavior === "generates nothing") {
                return;
            }

            fs.mkdirSync(pathJoin(params.resourcesDirPath, "theme"), {
                recursive: true
            });
        }
    );
}

beforeEach(() => {
    vi.clearAllMocks();

    // realpath: on macOS os.tmpdir() is a symlink, and we compare resolved paths.
    projectDirPath = fs.realpathSync(
        fs.mkdtempSync(pathJoin(os.tmpdir(), "keycloakify-api-test-"))
    );

    // The bundler output the generator reads from.
    fs.mkdirSync(pathJoin(projectDirPath, "dist"));

    getBuildContextMock.mockReturnValue({
        projectDirPath,
        projectBuildDirPath: pathJoin(projectDirPath, "dist")
    });

    setGeneratorBehavior("generates resources");
});

afterEach(() => {
    fs.rmSync(projectDirPath, { recursive: true, force: true });
    delete process.env[VITE_PLUGIN_SUB_SCRIPTS_ENV_NAMES.RUN_POST_BUILD_SCRIPT];
});

describe("generateResources - refuses to delete what it doesn't own", () => {
    it("refuses an empty resourcesDirPath", async () => {
        await expect(
            generateResources({ projectDirPath, resourcesDirPath: "" })
        ).rejects.toThrow("can't be empty");

        expect(generateThemeResourcesMock).not.toHaveBeenCalled();
    });

    it("refuses the project directory itself", async () => {
        await expect(
            generateResources({ projectDirPath, resourcesDirPath: "." })
        ).rejects.toThrow("project directory or one of its parents");

        expect(generateThemeResourcesMock).not.toHaveBeenCalled();
    });

    it("refuses a parent of the project directory", async () => {
        await expect(
            generateResources({ projectDirPath, resourcesDirPath: ".." })
        ).rejects.toThrow("project directory or one of its parents");

        expect(generateThemeResourcesMock).not.toHaveBeenCalled();
    });

    it("refuses a non empty directory it didn't generate, without touching it", async () => {
        const srcDirPath = pathJoin(projectDirPath, "src");

        fs.mkdirSync(srcDirPath);
        fs.writeFileSync(pathJoin(srcDirPath, "main.tsx"), "precious");

        await expect(
            generateResources({ projectDirPath, resourcesDirPath: "src" })
        ).rejects.toThrow("wasn't generated by generateResources()");

        expect(generateThemeResourcesMock).not.toHaveBeenCalled();
        expect(fs.readFileSync(pathJoin(srcDirPath, "main.tsx")).toString("utf8")).toBe(
            "precious"
        );
    });

    it("refuses a path that exists as a file", async () => {
        fs.writeFileSync(pathJoin(projectDirPath, "out"), "");

        await expect(
            generateResources({ projectDirPath, resourcesDirPath: "out" })
        ).rejects.toThrow("isn't a directory");

        expect(generateThemeResourcesMock).not.toHaveBeenCalled();
    });
});

describe("generateResources - preconditions", () => {
    it("refuses to run before the bundler build", async () => {
        fs.rmSync(pathJoin(projectDirPath, "dist"), { recursive: true });

        await expect(
            generateResources({ projectDirPath, resourcesDirPath: "out" })
        ).rejects.toThrow("Run your bundler build first");

        expect(generateThemeResourcesMock).not.toHaveBeenCalled();
    });

    it("refuses to run from within the postBuild hook", async () => {
        process.env[VITE_PLUGIN_SUB_SCRIPTS_ENV_NAMES.RUN_POST_BUILD_SCRIPT] =
            JSON.stringify({});

        await expect(
            generateResources({ projectDirPath, resourcesDirPath: "out" })
        ).rejects.toThrow("loop indefinitely");

        expect(getBuildContextMock).not.toHaveBeenCalled();
    });
});

describe("generateResources - happy path", () => {
    it("generates into a fresh directory and marks it", async () => {
        const { resourcesDirPath } = await generateResources({
            projectDirPath,
            resourcesDirPath: "out"
        });

        expect(resourcesDirPath).toBe(pathJoin(projectDirPath, "out"));
        expect(fs.existsSync(pathJoin(resourcesDirPath, "theme"))).toBe(true);
        expect(fs.existsSync(pathJoin(resourcesDirPath, MARKER_BASENAME))).toBe(true);
        expect(runPostBuildScriptMock).toHaveBeenCalledOnce();
    });

    it("accepts an empty directory", async () => {
        fs.mkdirSync(pathJoin(projectDirPath, "out"));

        await expect(
            generateResources({ projectDirPath, resourcesDirPath: "out" })
        ).resolves.toBeTruthy();
    });

    it("accepts a directory a previous call generated", async () => {
        await generateResources({ projectDirPath, resourcesDirPath: "out" });

        await expect(
            generateResources({ projectDirPath, resourcesDirPath: "out" })
        ).resolves.toBeTruthy();

        expect(generateThemeResourcesMock).toHaveBeenCalledTimes(2);
    });

    it("never writes outside the directory it was given", async () => {
        await generateResources({ projectDirPath, resourcesDirPath: "out" });

        expect(fs.readdirSync(projectDirPath).sort()).toEqual(["dist", "out"]);
    });
});

describe("generateResources - postconditions", () => {
    it("throws rather than returning a path to nothing", async () => {
        setGeneratorBehavior("generates nothing");

        await expect(
            generateResources({ projectDirPath, resourcesDirPath: "out" })
        ).rejects.toThrow("no resources were generated");

        expect(runPostBuildScriptMock).not.toHaveBeenCalled();
    });
});
